apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signport-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: signport-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-apps/
    repoURL: 'https://github.com/stakater/signport.git'
    targetRevision: main
    directory:
       recurse: true
  project: signport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
