apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-stage
  namespace: openshift-stakater-gitops
spec:
  destination:
    namespace: openshift-stakater-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/00-argocd-apps/02-stage/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
      recurse: true
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

