apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-build-inventory
  namespace: openshift-gitops 
  labels:
    stakater.com/tenant: veeru
    stakater.com/env: build
    stakater.com/kind: build     
spec:
  destination:
    namespace: veeru-build
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/apps/01-stakater-nordmart-inventory/00-build
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true