
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-operator
  namespace: openshift-stakater-gitops
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 03-sre/02-stage-prod/tenant-operator-config
    repoURL: 'http://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

