apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: demo
spec:
  quota: medium
  owners:
    groups:
      - azure-gabbar-owner
  editors:
    groups:
      - azure-gabbar-editor
  viewers:
    groups:
      - azure-gabbar-viewer
  namespaces:
  - demo1
  - demo2
