application: 
 applicationName: "review"
 configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
 