apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-prod-stakater-nordmart-inventory
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: veeru
    stakater.com/env: prod
    stakater.com/kind: prod    
spec:
  destination:
    namespace: veeru-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/01-stakater-nordmart-inventory/03-prod
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true